language: python

addons:
  sonarcloud:
    organization: "arturfog-github"
    token:
      secure: "EkbBnnRu7aGDS7Nn8+YjicaBh3YNwARSgvAx78e9C+tPpdJWnZ/tbOT/Hphm+Pv2HHOkE/f1SvWHRoe7SJlwIIrN4JSKnpqdUOa2id6U1ipnYEd0Sc9Nzt/p0DgpXWQ6vCfemATUN9WZYLnKhHO8gRfGib/Zbs4fcVuBMHN+ACAB4fmhkO/I46XVMY1/dgrUJVbTdrEwC3qvAXrcwM+kupmqJbTZiO90FTenVBqKlK7HtcJTbVS2zwEre/OxaTv338Fm63eQvdDpr/cPO816JiK7uOijVUyW+w5qyGdfhnBUxKLNJ86D2/+GqVHYfsXYT/3j8S0H6CJFVtvpi1ic2nOxsT/jfrsWrNTZniRh0LsmpCx9tQkxzLFB8fvUx4T0vg79tpjpqiFnI34+Oi9KWf5EH471ovlJ/rbQ631/dfueW0gzQgJkGPglCm2+m4rTtcMVQMZO6nnZtw0Hr7rX3SfGvCrTvrdq0iDUIFaHtabFJodfeIPUL7o4vxfJAA8Ou9yXeuAsqsQ9R0LH8v55Wr0ANf1Ofl6yz8PubLfbPxCOihbiWjvEhoA+dHtsNMhAcMiflDr4PU7kLIRNNWjiHqOmEetSZ4253LNNo/vu990XNU2MhJqOZvkAS4fZKKwt2KQw31yBa84TfCjrYF4EN5ovwBWAhvMqV8klBm1ubv8="

script:
        - ls
