# Generated by Django 2.1.3 on 2018-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(help_text='URL', max_length=200, unique=True)),
                ('ip', models.CharField(help_text='IP', max_length=64)),
                ('ttl', models.IntegerField(help_text='TTL')),
                ('comment', models.CharField(help_text='Comment', max_length=250)),
            ],
        ),
    ]
