# Generated by Django 2.1.5 on 2019-01-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_hostsources'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hits',
            field=models.IntegerField(help_text='Hits', null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='last_access',
            field=models.DateTimeField(null=True),
        ),
    ]
