# Generated by Django 2.1.5 on 2019-01-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_auto_20190126_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='traffic',
            name='hits',
            field=models.IntegerField(help_text='Hits', null=True),
        ),
    ]
