name: pydnshelper
version: '0.1.0'
summary: DNS sever focused on security with web ui.
description: |
    DNS sever focused on security with web ui.

grade: stable
confinement: strict

apps: 
  pydnshelper:
    command: dnsserver/manage.py runserver
    plugs:
      - network

parts:
  pydnshelper:
    plugin: python
    python-version: python3
    source: https://github.com/arturfog/pydnsHelper.git
