name: pydnshelper
version: '0.1.0'
summary: DNS server focused on security with web ui.
description: DNS server focused on security with web ui.
grade: 'stable'
confinement: 'strict'

apps:
  pydnshelper:
    daemon: simple
    plugs: [network-bind]
    environment:
            LC_ALL: C.UTF-8
            LANG: C.UTF-8
    command: python bin/manage.py runserver 0.0.0.0:8000

parts:
  pydnshelper:
    plugin: python
    source: .
    python-version: python3
    requirements: ./requirements.txt
    stage-packages:
       - libgetdns1
       - libgetdns-dev

  dnserver:
    plugin: copy
    files:
      ./dnsserver: bin
